### ISSUE TITLE
Deployment line 153 causes launch failure

### ISSUE THREAD

**Issue by ScriptPup** [Forecaster/UniversalVTTExport_to_FGModule#1]
Line 153 in the script in the "deployment" folder causes the script to fail. Commenting it out seems to resolve, so probably just an artifact from development or something. 

```
_testb as fg_module
```

Thanks!

**Comment by Forecaster** [comment]
That line is removed in my local version of this file (among other changes), but as of the executable update this directory is obsolete, as it's purpose was to provide a single-file solution with the other library files baked in, but the executable makes this unnecessary, hence why I didn't update this file in this commit. I should delete it to reduce confusion.
